name = "korean-lib"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# Cloudflare Pages 설정
[env.production]
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

